version: '3.4'

services:
  captest:
    image: ${DOCKER_REGISTRY-}captest
    build:
      context: .
      dockerfile: CapTest/Dockerfile
  rabbitmq:
    image: rabbitmq:3.8-management # RabbitMQ 版本
    ports:
      - "5672:5672" # RabbitMQ 默认端口
      - "80:15672" # RabbitMQ 管理界面端口
    hostname: rabbitmq # 主机名
    container_name: "wycs_rabbitmq3.8"
    restart: always
    environment:
      RABBITMQ_ERLANG_COOKIE: "unique-erlang-cookie" # Erlang cookie
      RABBITMQ_DEFAULT_USER: "123123" # 設置自定義用戶名
      RABBITMQ_DEFAULT_PASS: "123123" # 設置自定義密碼
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # 持久化数据
volumes:
  rabbitmq_data:
    driver: local
